apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      labels: 
        app: backend
    spec:
      containers:
      - name: chatapp-backend
        image: parth1509/chatbackend:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          value: "mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: jwt 
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: cloud_name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: api_key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: api_secret
        - name: PORT
          value: "5001"
        
        # **# ⚡ ADDED RESOURCES FOR HPA**
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
