apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: chat-app
spec:
  clusterIP: None               # Headless service required for StatefulSet
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
