apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mongodb-vpa
  namespace: chat-app
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongodb
  updatePolicy:
    updateMode: "Recreate"   # Required for StatefulSet
  resourcePolicy:
    containerPolicies:
    - containerName: chatapp-mongodb
      minAllowed:
        cpu: 100m
        memory: 512Mi
      maxAllowed:
        cpu: 2
        memory: 4Gi


    

 






