kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chat-app-manager-binding
  namespace: chat-app
subjects:
- kind: ServiceAccount
  name: manager-svc
  namespace: chat-app
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: chat-app-manager
  apiGroup: rbac.authorization.k8s.io