kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: chat-app
  name: chat-app-manager
rules:
- apiGroups: ["","rbac.authorization.k8s.io","apps","extensions","batch","networking.k8s.io","policy","storage.k8s.io","apiextensions.k8s.io"]
  resources: ["pods","deployment","services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get","apply","list", "watch", "create", "delete", "update"]
