apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/backup
    type: DirectoryOrCreate
